import Head from 'next/head';
import Navbar from './navbar';

type PropLayout = {
    children: React.ReactNode;
    title: string;
    description: string;
};

export default function Layout({ children, title, description }: PropLayout) {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta
                    name={description}
                    content="Generated by create next app"
                />
                <link rel="icon" href="/logo-ico.svg" />
            </Head>
            <main className="h-screen bg-quartet w-full flex flex-col items-center">
                <Navbar />
                {children}
            </main>
        </>
    );
}
